#Define o nome do mundo para onde os players serão teleportados, e as coordenadas para o teleporte fixo.
spawn_world:
  name: world

#Mensagem para quando o jogador for teleportado randomicamente, delay em segundos para a exibição da mensagem
welcome_message:
  enabled: false
  message: Bem-vindo! Você foi transportado para uma coordenada aleatória para começar seu jogo!
  delay: 1

#Define se o teleporte será randomico ou fixo.
random_tp: true

#Define as coordenadas do teleporte fixo.
fixed_teleport:
  fix_x: 0
  fix_y: 0
  fix_z: 0

#Define o limite mínimo e o limite máximo ('min_range' e 'max_range') de blocos que o player será teleportado.
random_teleport:
  min_range: 100
  max_range: 1000